17:36:04 15 May 2024 UTC: INFO: BaseLog.py(120): Process id = 1116643
17:36:04 15 May 2024 UTC: WARNING: BaseLog.py(123): Config file /home/jails/uwssc/gliderjail/home/sg195/sg195.conf was not found
17:36:04 15 May 2024 UTC: INFO: Utils.py(1011): Basestation version: 3.0.2; QC version: 1.12
17:36:04 15 May 2024 UTC: INFO: Utils.py(1017): Python version 3.10.10
17:36:04 15 May 2024 UTC: INFO: Utils.py(1031): Numpy version 1.25.0
17:36:04 15 May 2024 UTC: INFO: Utils.py(1046): Scipy version 1.10.1
17:36:04 15 May 2024 UTC: INFO: Utils.py(1066): seawater version 3.3.4
17:36:04 15 May 2024 UTC: INFO: Base.py(1479): Invoked with command line [/usr/local/basestation3/Base.py --mission_dir /home/jails/uwssc/gliderjail/home/sg195 --verbose --make_mission_timeseries --daemon --nice 10 --base_log /home/jails/uwssc/gliderjail/home/sg195/baselog_240515173602 --web_file_location=http://iop.apl.washington.edu/seaglider/sg195/current/data --reply_addr=gbs2@uw.edu --config /home/jails/uwssc/gliderjail/home/sg195/sg195.conf --delete_upload_files ]
17:36:04 15 May 2024 UTC: INFO: Base.py(1481): PID:1116737
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): volmax value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): rho0 value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): hd_a value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): hd_b value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): hd_c value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): abs_compress value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): therm_expan value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: WARNING: CalibConst.py(120): temp_ref value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning. (Max message count exceeded)
17:36:04 15 May 2024 UTC: INFO: Base.py(1529): Started processing 17:36:04 15 May 2024 GMT
17:36:04 15 May 2024 UTC: INFO: Base.py(1572): Instrument ID = 195
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /usr/local/basestation3/etc/.pagers for  lategps recov critical drift
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/sg1i1w4wpibg9m8s77e19st14w,slack,gpsddmm)
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/71kp13t63ifummqbhxzniw18go,slack,alerts)
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/5t1u7ab147dstbh5iq79h48spy,slack,critical)
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:04 15 May 2024 UTC: INFO: CommLog.py(113): prefix:dive:2 calls_made:1 call_cycle:0 
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /usr/local/basestation3/etc/.pagers
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers for  lategps recov critical drift
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (7247147343@vtext.com,gps,alerts,recov)
17:36:04 15 May 2024 UTC: INFO: CommLog.py(113): prefix:dive:2 calls_made:1 call_cycle:0 
17:36:04 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers
17:36:04 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /usr/local/basestation3/etc/pagers.yml found - skipping
17:36:04 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /home/jails/uwssc/gliderjail/home/sg195/pagers.yml found - skipping
17:36:04 15 May 2024 UTC: INFO: Base.py(1635): Processing comm_merged.log
17:36:04 15 May 2024 UTC: INFO: Base.py(1664): Finished processing comm_merged.log
17:36:04 15 May 2024 UTC: INFO: Base.py(1784): Processing seaglider selftests
17:36:04 15 May 2024 UTC: INFO: Base.py(1820): No new selftests to processed
17:36:04 15 May 2024 UTC: INFO: Base.py(1822): Processing pdoscmd.bat logs
17:36:04 15 May 2024 UTC: INFO: Base.py(1841): No pdos logfiles found to process
17:36:04 15 May 2024 UTC: INFO: Base.py(1848): Processing dive(s)
17:36:04 15 May 2024 UTC: INFO: Base.py(536): Processing /home/jails/uwssc/gliderjail/home/sg195/sg0002lz
17:36:04 15 May 2024 UTC: INFO: Base.py(1048): Checking fragment /home/jails/uwssc/gliderjail/home/sg195/sg0002lz.1a.x00
17:36:04 15 May 2024 UTC: INFO: Base.py(706): Processing /home/jails/uwssc/gliderjail/home/sg195/sg0002lz.r in process_file_group
17:36:04 15 May 2024 UTC: INFO: Base.py(861): Removing secrets from /home/jails/uwssc/gliderjail/home/sg195/p1950002.log
17:36:04 15 May 2024 UTC: INFO: Base.py(536): Processing /home/jails/uwssc/gliderjail/home/sg195/sg0002dz
17:36:04 15 May 2024 UTC: INFO: Base.py(1048): Checking fragment /home/jails/uwssc/gliderjail/home/sg195/sg0002dz.1a.x00
17:36:04 15 May 2024 UTC: INFO: Base.py(1048): Checking fragment /home/jails/uwssc/gliderjail/home/sg195/sg0002dz.1a.x01
17:36:04 15 May 2024 UTC: INFO: Base.py(706): Processing /home/jails/uwssc/gliderjail/home/sg195/sg0002dz.r in process_file_group
17:36:04 15 May 2024 UTC: WARNING: DataFiles.py(265): No handler found for columns ['wlbb2fl.sig470nm', 'wlbb2fl.sig700nm', 'wlbb2fl.sig695nm'] - using default handler
17:36:04 15 May 2024 UTC: INFO: Base.py(536): Processing /home/jails/uwssc/gliderjail/home/sg195/sg0002kz
17:36:04 15 May 2024 UTC: INFO: Base.py(1048): Checking fragment /home/jails/uwssc/gliderjail/home/sg195/sg0002kz.1a.x00
17:36:04 15 May 2024 UTC: INFO: Base.py(1048): Checking fragment /home/jails/uwssc/gliderjail/home/sg195/sg0002kz.1a.x01
17:36:04 15 May 2024 UTC: INFO: Base.py(1048): Checking fragment /home/jails/uwssc/gliderjail/home/sg195/sg0002kz.1a.x02
17:36:04 15 May 2024 UTC: INFO: Base.py(706): Processing /home/jails/uwssc/gliderjail/home/sg195/sg0002kz.r in process_file_group
17:36:04 15 May 2024 UTC: INFO: Base.py(1881): Processed dive(s) [2]
17:36:04 15 May 2024 UTC: INFO: Base.py(1957): Dives to process = [2]
17:36:04 15 May 2024 UTC: INFO: Base.py(1986): Processing (/home/jails/uwssc/gliderjail/home/sg195/p1950002) for profiles
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(1624): Loading data from original files
17:36:04 15 May 2024 UTC: INFO: FlightModel.py(844): Updating FM parameters using per-dive estimations for dive 1 (1.00,1.00)
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: volmax=53235.7
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: vbdbias=118.123
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: hd_a=0.00354813
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: hd_b=0.0112202
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: hd_c=5.7e-06
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: hd_s=-0.25
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: abs_compress=4.55616e-06
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: therm_expan=7.05e-05
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: temp_ref=15
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: glider_length=1.8
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2593): FM: rho0=1027.5
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2613): auxcompass data not present, auxPressure data not present
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2771): Not using auxcompass Not using auxPressure
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2846): Directive: correct_thermal_inertia_effects
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2846): Directive: detect_conductivity_anomalies
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2846): Directive: no_interp_gc_temperatures
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2846): Directive: no_interp_suspect_thermal_inertia_salinities
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2846): Directive: detect_vbd_bleed
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(2846): Directive: detect_slow_apogee_flow
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(3741): ct_type:gun-style Seabird unpumped CTD
17:36:04 15 May 2024 UTC: INFO: QC.py(517): Changed (14/174) 3 4 6 7 10:13 15 17:20 22 to QC_PROBABLY_BAD because raw temperature spikes
17:36:04 15 May 2024 UTC: INFO: QC.py(538): Changed (1/174) 174 to QC_BAD because raw salinity below bound
17:36:04 15 May 2024 UTC: INFO: QC.py(554): Changed (1/174) 174 to QC_BAD because bad raw salinity indicates raw conductivity issues
17:36:04 15 May 2024 UTC: INFO: QC.py(599): Changed (6/174) 4 10 14 17 18 23 to QC_PROBABLY_BAD because raw conductivity spikes
17:36:04 15 May 2024 UTC: INFO: QC.py(254): Changed (14/174) 3 4 6 7 10:13 15 17:20 22 to QC_PROBABLY_BAD because changed raw temp implies changed raw salinity
17:36:04 15 May 2024 UTC: INFO: QC.py(254): Changed (2/174) 14 23 to QC_PROBABLY_BAD because changed raw cond implies changed raw salinity
17:36:04 15 May 2024 UTC: INFO: QC.py(517): Changed (14/174) 3 4 6 7 10:13 15 17:20 22 to QC_INTERPOLATED because temperature spikes
17:36:04 15 May 2024 UTC: INFO: QC.py(538): Changed (1/174) 174 to QC_BAD because salinity below bound
17:36:04 15 May 2024 UTC: INFO: QC.py(554): Changed (1/174) 174 to QC_BAD because bad salinity indicates conductivity issues
17:36:04 15 May 2024 UTC: INFO: QC.py(599): Changed (6/174) 4 10 14 17 18 23 to QC_INTERPOLATED because conductivity spikes
17:36:04 15 May 2024 UTC: WARNING: MakeDiveProfiles.py(5062): Mass of vehicle in sg_calib_constants (53692.0) does not match $MASS in log file (53765.0); using sg_calib_constants
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(5162): Changed (40/174) 71:110 to QC_BAD because slow apogee CT flow
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(5351): Changed (29/174) 1:29 to QC_BAD because during VBD bleed
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(5475): Changed (1/174) 173 to QC_BAD because end of climb
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(5539): Changed (71/174) 1:29 71:110 173 174 to QC_BAD because bad corrected temperature and conductivity suggests bad salinity
17:36:04 15 May 2024 UTC: INFO: MakeDiveProfiles.py(5704): Using 1-mode thermal-inertia correction.
17:36:04 15 May 2024 UTC: INFO: QC.py(254): Changed (71/174) 1:29 71:110 173 174 to QC_BAD because changed corrected salin implies changed speed
17:36:04 15 May 2024 UTC: INFO: TempSalinityVelocity.py(1081): 0: max temp_c diff: 0.02C TI time: 0.004s loop: 0.003s
17:36:05 15 May 2024 UTC: INFO: TempSalinityVelocity.py(1081): 1: max temp_c diff: 0.03C TI time: 0.004s loop: 0.003s
17:36:05 15 May 2024 UTC: INFO: TempSalinityVelocity.py(1081): 2: max temp_c diff: 0.03C TI time: 0.004s loop: 0.003s
17:36:05 15 May 2024 UTC: INFO: TempSalinityVelocity.py(1505): TSV exiting after 2 iterations
17:36:05 15 May 2024 UTC: INFO: TempSalinityVelocity.py(1507): max_temp_c_diff = 0.03C
17:36:05 15 May 2024 UTC: INFO: TempSalinityVelocity.py(1555): Changed (1/174) 172 to QC_PROBABLY_BAD because TS bad extrapolation
17:36:05 15 May 2024 UTC: INFO: MakeDiveProfiles.py(6188): 0 (0.00%) HDM speeds are QC_BAD; 0 (0.00%) are stalled (174)
17:36:05 15 May 2024 UTC: INFO: MakeDiveProfiles.py(6398): Estimated total flight and drift time: 1642.5s (SM: 230.9s)
17:36:05 15 May 2024 UTC: WARNING: MakeDiveProfiles.py(6429): Substantial unmodeled flight time (48.7% of total time); DAC is bad.
17:36:05 15 May 2024 UTC: INFO: MakeDiveProfiles.py(6684): Computing QC_BAD depth-average current.
17:36:05 15 May 2024 UTC: INFO: MakeDiveProfiles.py(6765): DAC east: -6.59 cm/s DAC north: -3.07 cm/s
17:36:05 15 May 2024 UTC: INFO: MakeDiveProfiles.py(6896): Starting sensor extensions data processing
17:36:05 15 May 2024 UTC: INFO: aa4330_ext.py(980): Changed (2/174) 1 2 to QC_BAD because bad aa4330 oyxgen
17:36:05 15 May 2024 UTC: INFO: QC.py(254): Changed (14/174) 3 4 6 7 10:13 15 17:20 22 to QC_INTERPOLATED because changed temperature implies changed aa4330 oxygen
17:36:05 15 May 2024 UTC: INFO: QC.py(254): Changed (1/174) 172 to QC_PROBABLY_BAD because changed salinity implies changed aa4330 oxygen
17:36:05 15 May 2024 UTC: INFO: QC.py(254): Changed (69/174) 3:29 71:110 173 174 to QC_BAD because changed salinity implies changed aa4330 oxygen
17:36:05 15 May 2024 UTC: INFO: MakeDiveProfiles.py(6900): Finished sensor extensions data processing
17:36:05 15 May 2024 UTC: INFO: BaseNetCDF.py(368): /usr/local/basestation3/etc/NODC.yml does not exist - skipping
17:36:06 15 May 2024 UTC: INFO: BaseNetCDF.py(368): /usr/local/basestation3/etc/NODC.yml does not exist - skipping
17:36:06 15 May 2024 UTC: INFO: BaseDotFiles.py(1556): No .extensions file /usr/local/basestation3/etc/.extensions found
17:36:06 15 May 2024 UTC: INFO: BaseDotFiles.py(1474): Starting processing on .extensions section(s):('postnetcdf',)
17:36:06 15 May 2024 UTC: INFO: BaseDotFiles.py(1542): Finished processing on .extensions
17:36:06 15 May 2024 UTC: INFO: Base.py(2072): Backing up /home/jails/uwssc/gliderjail/home/sg195/cmdfile to /home/jails/uwssc/gliderjail/home/sg195/cmdfile.2.0
17:36:06 15 May 2024 UTC: INFO: BaseDB.py(1346): logParameterChanges db opened
17:36:06 15 May 2024 UTC: INFO: BaseDB.py(1006): version not set, checking table existence
17:36:06 15 May 2024 UTC: INFO: BaseDB.py(1017): stepping DB schema from 0 to 1
17:36:06 15 May 2024 UTC: ERROR: could not check schema:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 1023, in checkSchema
    mycon.cursor().execute(f"ALTER TABLE calls ADD COLUMN sms INTEGER;")
sqlite3.OperationalError: no such table: calls

17:36:06 15 May 2024 UTC: ERROR: BaseDB.py(1372): no such table: changes inserting parameter changes
17:36:06 15 May 2024 UTC: ERROR: BaseDB.py(1372): no such table: changes inserting parameter changes
17:36:06 15 May 2024 UTC: ERROR: BaseDB.py(1372): no such table: changes inserting parameter changes
17:36:06 15 May 2024 UTC: INFO: BaseDB.py(1384): logParameterChanges db closed
17:36:06 15 May 2024 UTC: INFO: Utils.py(1011): Basestation version: 3.0.2; QC version: 1.12
17:36:06 15 May 2024 UTC: INFO: Utils.py(1017): Python version 3.10.10
17:36:06 15 May 2024 UTC: INFO: Utils.py(1031): Numpy version 1.25.0
17:36:06 15 May 2024 UTC: INFO: Utils.py(1046): Scipy version 1.10.1
17:36:06 15 May 2024 UTC: INFO: Utils.py(1066): seawater version 3.3.4
17:36:06 15 May 2024 UTC: INFO: FlightModel.py(3712): Exit is False
17:36:07 15 May 2024 UTC: INFO: FlightModel.py(2297): Started FM cycle 2
17:36:07 15 May 2024 UTC: INFO: FlightModel.py(2356): New dive 2 restarting from dive 1 (0.00354813,0.0112202)
17:36:07 15 May 2024 UTC: INFO: FlightModel.py(2427): dives_to_update:[2]
17:36:07 15 May 2024 UTC: INFO: FlightModel.py(2609): Early bias dives so far [2]
17:36:07 15 May 2024 UTC: INFO: FlightModel.py(2611): <Dive 2 pitch_d: 11.0 p: 49.1dbar vbias: 156.0cc (118.1cc) abs_compress=2.256e-06 RMS=1.2573cm/s>
17:36:08 15 May 2024 UTC: INFO: FlightModel.py(3534):  Reprocess dive 2: (False, False, False, True, True)
17:36:08 15 May 2024 UTC: INFO: FlightModel.py(3535):   v: 37.84 [155.96 118.12] ac: 0.505 [2.256e-06 4.55616e-06]
17:36:08 15 May 2024 UTC: INFO: FlightModel.py(3581): Reprocess dives: [2]
17:36:12 15 May 2024 UTC: INFO: FlightModel.py(3608): Back from Reprocess.py - see /home/jails/uwssc/gliderjail/home/sg195/flight/Reprocess_0002_1715794568.log for details
17:36:12 15 May 2024 UTC: INFO: FlightModel.py(3621): Dive 2 sucesfully processed
17:36:12 15 May 2024 UTC: INFO: FlightModel.py(2427): dives_to_update:[2]
17:36:12 15 May 2024 UTC: INFO: FlightModel.py(2609): Early bias dives so far [2]
17:36:12 15 May 2024 UTC: INFO: FlightModel.py(2611): <Dive 2 pitch_d: 11.0 p: 49.1dbar vbias: 156.0cc (156.0cc) abs_compress=2.256e-06 RMS=1.2573cm/s>
17:36:13 15 May 2024 UTC: INFO: Base.py(2196): FM files updated ['/home/jails/uwssc/gliderjail/home/sg195/p1950002.nc']
17:36:13 15 May 2024 UTC: INFO: Base.py(1363): Extension script /home/jails/uwssc/gliderjail/home/sg195/.post_dive not found
17:36:13 15 May 2024 UTC: INFO: Base.py(2221): Starting netcdf load to db
17:36:13 15 May 2024 UTC: INFO: BaseDB.py(1090): loadDB db opened
17:36:13 15 May 2024 UTC: INFO: BaseDB.py(1006): version not set, checking table existence
17:36:13 15 May 2024 UTC: INFO: BaseDB.py(1017): stepping DB schema from 0 to 1
17:36:13 15 May 2024 UTC: ERROR: could not check schema:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 1023, in checkSchema
    mycon.cursor().execute(f"ALTER TABLE calls ADD COLUMN sms INTEGER;")
sqlite3.OperationalError: no such table: calls

17:36:13 15 May 2024 UTC: ERROR: Failed to add /home/jails/uwssc/gliderjail/home/sg195/p1950002.nc to mission sqlite db:
Traceback (most recent call last):
  File "/usr/local/basestation3/Base.py", line 2230, in main
    BaseDB.loadDB(base_opts, ncf, run_dive_plots=False)
  File "/usr/local/basestation3/BaseDB.py", line 1100, in loadDB
    loadFileToDB(base_opts, cur, filename, con, run_dive_plots=run_dive_plots)
  File "/usr/local/basestation3/BaseDB.py", line 286, in loadFileToDB
    cur.execute(f"DELETE FROM dives WHERE dive={dive};")
sqlite3.OperationalError: no such table: dives

17:36:13 15 May 2024 UTC: INFO: BaseDB.py(1090): loadDB db opened
17:36:13 15 May 2024 UTC: INFO: BaseDB.py(1006): version not set, checking table existence
17:36:13 15 May 2024 UTC: INFO: BaseDB.py(1017): stepping DB schema from 0 to 1
17:36:13 15 May 2024 UTC: ERROR: could not check schema:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 1023, in checkSchema
    mycon.cursor().execute(f"ALTER TABLE calls ADD COLUMN sms INTEGER;")
sqlite3.OperationalError: no such table: calls

17:36:13 15 May 2024 UTC: ERROR: Failed to add /home/jails/uwssc/gliderjail/home/sg195/p1950002.nc to mission sqlite db:
Traceback (most recent call last):
  File "/usr/local/basestation3/Base.py", line 2230, in main
    BaseDB.loadDB(base_opts, ncf, run_dive_plots=False)
  File "/usr/local/basestation3/BaseDB.py", line 1100, in loadDB
    loadFileToDB(base_opts, cur, filename, con, run_dive_plots=run_dive_plots)
  File "/usr/local/basestation3/BaseDB.py", line 286, in loadFileToDB
    cur.execute(f"DELETE FROM dives WHERE dive={dive};")
sqlite3.OperationalError: no such table: dives

17:36:13 15 May 2024 UTC: INFO: Base.py(2233): netcdf load to db done
17:36:13 15 May 2024 UTC: INFO: Base.py(2247): Starting per-dive plots
17:36:13 15 May 2024 UTC: INFO: BasePlot.py(96): plot_dives db opened
17:36:13 15 May 2024 UTC: INFO: BasePlot.py(101): Plotting /home/jails/uwssc/gliderjail/home/sg195/p1950002.nc
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str bad aa4330 oyxgen
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed temperature implies changed aa4330 oxygen
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str bad aa4330 oyxgen
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed temperature implies changed aa4330 oxygen
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:18 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(253): Starting dive_vert_vel
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(408): Basestation: hd_a:0.003548 hd_b:0.011220 hd_c:0.000006 mass:53.692 rho:1027.5
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(418): LogFile: hd_a:0.003800 hd_b:0.010000 hd_c:0.000010 mass:53.765 rho:1023.0
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(441): Using: hd_a:0.003548 hd_b:0.011220 hd_c:0.000006 mass:53.692 rho:1023.0
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(571): Search from -450.0 cc to 500.0 cc
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(574): vol range min:52248.38, max:53090.98, mean:52637.96
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 0 CC:-450.0 vert_v:-10.68
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 1 CC:500.0 vert_v:12.48
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 2 CC:0.0 vert_v:-2.28
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 3 CC:250.0 vert_v:5.86
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 4 CC:125.0 vert_v:1.48
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 5 CC:62.5 vert_v:-0.45
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 6 CC:93.8 vert_v:0.50
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 7 CC:78.1 vert_v:0.03
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 8 CC:70.3 vert_v:-0.20
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 9 CC:74.2 vert_v:-0.08
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 10 CC:76.2 vert_v:-0.02
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 11 CC:77.1 vert_v:0.02
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(657): implied_cvbd 2687, implied_volmax 53021.4, implied_max_smcc 536.6, implied_max_maxbuoy -319.3
17:36:19 15 May 2024 UTC: INFO: DiveVertVelocity.py(660): min SM_CC 205.5 based on density 1.02192 at 1.14m and 150cc to raise the antenna
17:36:19 15 May 2024 UTC: ERROR: Error inserting column implied_C_VBD - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:19 15 May 2024 UTC: ERROR: Error inserting column implied_volmax - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:19 15 May 2024 UTC: ERROR: Error inserting column implied_C_VBD_GSM - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:19 15 May 2024 UTC: ERROR: Error inserting column implied_volmax_GSM - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:19 15 May 2024 UTC: ERROR: Error inserting column implied_max_MAX_BUOY - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:19 15 May 2024 UTC: ERROR: Error inserting column implied_max_SM_CC - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:19 15 May 2024 UTC: ERROR: Error inserting column min_SM_CC - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:19 15 May 2024 UTC: ERROR: BaseDB.py(1222): Execution failed on sql 'SELECT dive, FROM dives WHERE dive <= 2 ORDER BY dive DESC LIMIT 10': near "FROM": syntax error could not fetch ['implied_volmax', 'implied_C_VBD'] for slope calculation
17:36:20 15 May 2024 UTC: INFO: DivePitchRoll.py(84): Starting dive_pitch_roll
17:36:20 15 May 2024 UTC: INFO: DivePitchRoll.py(272): implied_cpitch 2948.979557965925, implied_pitchgain 15.70574648859591
17:36:20 15 May 2024 UTC: ERROR: Error inserting column implied_C_PITCH - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:20 15 May 2024 UTC: ERROR: Error inserting column implied_PITCH_GAIN - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:20 15 May 2024 UTC: ERROR: BaseDB.py(1222): Execution failed on sql 'SELECT dive, FROM dives WHERE dive <= 2 ORDER BY dive DESC LIMIT 10': near "FROM": syntax error could not fetch ['implied_C_PITCH'] for slope calculation
17:36:20 15 May 2024 UTC: ERROR: plot_pitch_roll failed /home/jails/uwssc/gliderjail/home/sg195/p1950002.nc:
Traceback (most recent call last):
  File "/usr/local/basestation3/BasePlot.py", line 106, in plot_dives
    fig_list, file_list = plot_func(
  File "/usr/local/basestation3/Plotting/DivePitchRoll.py", line 470, in plot_pitch_roll
    fitc = scipy.stats.linregress(
  File "/opt/basestation/lib/python3.10/site-packages/scipy/stats/_stats_mstats_common.py", line 157, in linregress
    raise ValueError("Cannot calculate a linear regression "
ValueError: Cannot calculate a linear regression if all x values are identical

17:36:20 15 May 2024 UTC: INFO: Magcal.py(254): hard magcal PQR = [-12.84,54.00,51.35], converged=1, it=3
17:36:23 15 May 2024 UTC: INFO: Magcal.py(388): hard+soft magcal PQR = [287.48,44.96,-47.98], converged=1, it=11
17:36:23 15 May 2024 UTC: INFO: Magcal.py(394): hard+soft magcal abc = 1.000,0.332,-0.854,-0.191,1.099,0.253,0.739,0.166,0.641
17:36:23 15 May 2024 UTC: INFO: Magcal.py(400): distrusting soft-iron, using hard-only solution with identity for soft
17:36:24 15 May 2024 UTC: INFO: BasePlot.py(101): Plotting /home/jails/uwssc/gliderjail/home/sg195/p1950002.nc
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str bad aa4330 oyxgen
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed temperature implies changed aa4330 oxygen
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str bad aa4330 oyxgen
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed temperature implies changed aa4330 oxygen
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:28 15 May 2024 UTC: WARNING: QC.py(1344): Unclassified qc_str changed salinity implies changed aa4330 oxygen
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(253): Starting dive_vert_vel
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(408): Basestation: hd_a:0.003548 hd_b:0.011220 hd_c:0.000006 mass:53.692 rho:1027.5
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(418): LogFile: hd_a:0.003800 hd_b:0.010000 hd_c:0.000010 mass:53.765 rho:1023.0
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(441): Using: hd_a:0.003548 hd_b:0.011220 hd_c:0.000006 mass:53.692 rho:1023.0
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(571): Search from -450.0 cc to 500.0 cc
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(574): vol range min:52248.38, max:53090.98, mean:52637.96
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 0 CC:-450.0 vert_v:-10.68
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 1 CC:500.0 vert_v:12.48
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 2 CC:0.0 vert_v:-2.28
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 3 CC:250.0 vert_v:5.86
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 4 CC:125.0 vert_v:1.48
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 5 CC:62.5 vert_v:-0.45
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 6 CC:93.8 vert_v:0.50
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 7 CC:78.1 vert_v:0.03
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 8 CC:70.3 vert_v:-0.20
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 9 CC:74.2 vert_v:-0.08
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 10 CC:76.2 vert_v:-0.02
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(617): Bias HDM 11 CC:77.1 vert_v:0.02
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(657): implied_cvbd 2687, implied_volmax 53021.4, implied_max_smcc 536.6, implied_max_maxbuoy -319.3
17:36:28 15 May 2024 UTC: INFO: DiveVertVelocity.py(660): min SM_CC 205.5 based on density 1.02192 at 1.14m and 150cc to raise the antenna
17:36:28 15 May 2024 UTC: ERROR: Error inserting column implied_C_VBD - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:28 15 May 2024 UTC: ERROR: Error inserting column implied_volmax - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:28 15 May 2024 UTC: ERROR: Error inserting column implied_C_VBD_GSM - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:28 15 May 2024 UTC: ERROR: Error inserting column implied_volmax_GSM - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:29 15 May 2024 UTC: ERROR: Error inserting column implied_max_MAX_BUOY - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:29 15 May 2024 UTC: ERROR: Error inserting column implied_max_SM_CC - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:29 15 May 2024 UTC: ERROR: Error inserting column min_SM_CC - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:29 15 May 2024 UTC: ERROR: BaseDB.py(1222): Execution failed on sql 'SELECT dive, FROM dives WHERE dive <= 2 ORDER BY dive DESC LIMIT 10': near "FROM": syntax error could not fetch ['implied_volmax', 'implied_C_VBD'] for slope calculation
17:36:29 15 May 2024 UTC: INFO: DivePitchRoll.py(84): Starting dive_pitch_roll
17:36:29 15 May 2024 UTC: INFO: DivePitchRoll.py(272): implied_cpitch 2948.979557965925, implied_pitchgain 15.70574648859591
17:36:29 15 May 2024 UTC: ERROR: Error inserting column implied_C_PITCH - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:29 15 May 2024 UTC: ERROR: Error inserting column implied_PITCH_GAIN - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:29 15 May 2024 UTC: ERROR: BaseDB.py(1222): Execution failed on sql 'SELECT dive, FROM dives WHERE dive <= 2 ORDER BY dive DESC LIMIT 10': near "FROM": syntax error could not fetch ['implied_C_PITCH'] for slope calculation
17:36:29 15 May 2024 UTC: ERROR: plot_pitch_roll failed /home/jails/uwssc/gliderjail/home/sg195/p1950002.nc:
Traceback (most recent call last):
  File "/usr/local/basestation3/BasePlot.py", line 106, in plot_dives
    fig_list, file_list = plot_func(
  File "/usr/local/basestation3/Plotting/DivePitchRoll.py", line 470, in plot_pitch_roll
    fitc = scipy.stats.linregress(
  File "/opt/basestation/lib/python3.10/site-packages/scipy/stats/_stats_mstats_common.py", line 157, in linregress
    raise ValueError("Cannot calculate a linear regression "
ValueError: Cannot calculate a linear regression if all x values are identical

17:36:29 15 May 2024 UTC: INFO: Magcal.py(254): hard magcal PQR = [-12.84,54.00,51.35], converged=1, it=3
17:36:32 15 May 2024 UTC: INFO: Magcal.py(388): hard+soft magcal PQR = [287.48,44.96,-47.98], converged=1, it=11
17:36:32 15 May 2024 UTC: INFO: Magcal.py(394): hard+soft magcal abc = 1.000,0.332,-0.854,-0.191,1.099,0.253,0.739,0.166,0.641
17:36:32 15 May 2024 UTC: INFO: Magcal.py(400): distrusting soft-iron, using hard-only solution with identity for soft
17:36:33 15 May 2024 UTC: INFO: BasePlot.py(133): plot_dives db closed
17:36:33 15 May 2024 UTC: INFO: Base.py(2252): Per-dive plots complete
17:36:33 15 May 2024 UTC: INFO: BaseDotFiles.py(1556): No .extensions file /usr/local/basestation3/etc/.extensions found
17:36:33 15 May 2024 UTC: INFO: BaseDotFiles.py(1474): Starting processing on .extensions section(s):('dive',)
17:36:33 15 May 2024 UTC: INFO: BaseDotFiles.py(1542): Finished processing on .extensions
17:36:33 15 May 2024 UTC: INFO: BaseDotFiles.py(341): No .urls file /usr/local/basestation3/etc/.urls found - skipping pass 1
17:36:33 15 May 2024 UTC: INFO: BaseDotFiles.py(266): Starting processing on .urls pass(1)
17:36:33 15 May 2024 UTC: INFO: BaseDotFiles.py(331): Finished processing on .urls pass(1)
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-2963492-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-15566-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-766373-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-19345-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-20485-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-2961317-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-766476-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-16884-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=perdive","time":1715794593.1829522}
17:36:33 15 May 2024 UTC: INFO: MakeMissionTimeSeries.py(231): Making mission timeseries /home/jails/uwssc/gliderjail/home/sg195/sg195_Shilshole_Overnight_OCN_201__15May2024_timeseries.nc from files found in /home/jails/uwssc/gliderjail/home/sg195/
17:36:33 15 May 2024 UTC: INFO: BaseNetCDF.py(368): /usr/local/basestation3/etc/NODC.yml does not exist - skipping
17:36:33 15 May 2024 UTC: INFO: BasePlot.py(159): plot_mission db opened
17:36:33 15 May 2024 UTC: INFO: MissionEnergy.py(98): Starting mission_energy None
17:36:33 15 May 2024 UTC: ERROR: Failed database call:
Traceback (most recent call last):
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
sqlite3.OperationalError: no such table: dives

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/basestation3/Plotting/MissionEnergy.py", line 121, in mission_energy
    fg_df = pd.read_sql_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT dive,fg_kJ_used_10V,fg_kJ_used_24V,fg_batt_capacity_10V,fg_batt_capacity_24V,fg_ah_used_10V,fg_ah_used_24V,log_FG_AHR_10Vo,log_FG_AHR_24Vo FROM dives  ORDER BY dive ASC': no such table: dives

17:36:33 15 May 2024 UTC: INFO: MissionMotors.py(77): Starting mission_motors
17:36:33 15 May 2024 UTC: ERROR: Could not fetch needed columns:
Traceback (most recent call last):
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
sqlite3.OperationalError: no such table: gc

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/basestation3/Plotting/MissionMotors.py", line 94, in mission_motors
    df = pd.read_sql_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT dive,roll_rate,roll_i,pitch_rate,pitch_i,vbd_rate,vbd_i,vbd_secs,depth,vbd_eff,pitch_volts,roll_volts,vbd_volts from gc': no such table: gc

17:36:33 15 May 2024 UTC: INFO: MissionIntSensors.py(63): Starting mission_int_sensors
17:36:33 15 May 2024 UTC: ERROR: Could not fetch needed columns:
Traceback (most recent call last):
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
sqlite3.OperationalError: no such table: dives

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/basestation3/Plotting/MissionIntSensors.py", line 83, in mission_int_sensors
    df = pd.read_sql_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT dive,log_HUMID,log_INTERNAL_PRESSURE from dives  ORDER BY dive ASC': no such table: dives

17:36:34 15 May 2024 UTC: ERROR: Could not fetch needed columns:
Traceback (most recent call last):
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2202, in execute
    cur.execute(sql, *args)
sqlite3.OperationalError: no such table: dives

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/basestation3/Plotting/MissionDepthAngle.py", line 74, in mission_depthangle
    df = pd.read_sql_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 469, in read_sql_query
    return pandas_sql.read_query(
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2266, in read_query
    cursor = self.execute(sql, params)
  File "/opt/basestation/lib/python3.10/site-packages/pandas/io/sql.py", line 2214, in execute
    raise ex from exc
pandas.errors.DatabaseError: Execution failed on sql 'SELECT dive,log__SM_DEPTHo,log__SM_ANGLEo from dives': no such table: dives

17:36:34 15 May 2024 UTC: INFO: MissionMap.py(130): Starting mission_map
17:36:34 15 May 2024 UTC: ERROR: MissionMap.py(145): database error
17:36:34 15 May 2024 UTC: WARNING: MissionCommLog.py(80): No calls table - skipping
17:36:34 15 May 2024 UTC: ERROR: Could not fetch data:
Traceback (most recent call last):
  File "/usr/local/basestation3/Plotting/MissionProfiles.py", line 129, in mission_profiles
    cur.execute("SELECT dive FROM dives ORDER BY dive DESC LIMIT 1;")
sqlite3.OperationalError: no such table: dives

17:36:34 15 May 2024 UTC: INFO: BasePlot.py(204): plot_mission db closed
17:36:34 15 May 2024 UTC: INFO: MakeKML.py(1039): Started processing 17:36:34 15 May 2024 GMT
17:36:34 15 May 2024 UTC: INFO: MakeKML.py(450): Opened /home/jails/uwssc/gliderjail/home/sg195/targets.0.0 for processing
17:36:34 15 May 2024 UTC: INFO: MakeKML.py(464): ['NORTH', 'lat=4744.5', 'lon=-12223.75', 'radius=200', 'finish=000', 'goto=SOUTH']
17:36:34 15 May 2024 UTC: INFO: MakeKML.py(464): ['SOUTH', 'lat=4743.0', 'lon=-12223.75', 'radius=200', 'finish=180', 'goto=NORTH']
17:36:34 15 May 2024 UTC: INFO: MakeKML.py(1756): Finished processing 17:36:34 15 May 2024 GMT
17:36:34 15 May 2024 UTC: INFO: MakeKML.py(1760): Run time 0.448124 seconds
17:36:34 15 May 2024 UTC: INFO: BaseDotFiles.py(1556): No .extensions file /usr/local/basestation3/etc/.extensions found
17:36:34 15 May 2024 UTC: INFO: BaseDotFiles.py(1474): Starting processing on .extensions section(s):('global', 'mission')
17:36:34 15 May 2024 UTC: INFO: BaseDotFiles.py(1542): Finished processing on .extensions
17:36:34 15 May 2024 UTC: INFO: CommLog.py(113): prefix:
17:36:34 15 May 2024 UTC: INFO: Base.py(2615): Processing FM_IGNORE
17:36:34 15 May 2024 UTC: INFO: Base.py(2615): Processing MASS_MISMATCH
17:36:34 15 May 2024 UTC: WARNING: Base.py(2646): ALERT:FM_IGNORE
    WARNING: volmax value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: rho0 value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: hd_a value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: hd_b value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: hd_c value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: abs_compress value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: therm_expan value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: temp_ref value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
ALERT:MASS_MISMATCH
    WARNING: Mass of vehicle in sg_calib_constants (53692.0) does not match $MASS in log file (53765.0); using sg_calib_constants
Consult baselog_240515173602 for details.
17:36:34 15 May 2024 UTC: INFO: BaseDB.py(1171): addValToDB db opened
17:36:34 15 May 2024 UTC: ERROR: Error inserting column alerts - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:34 15 May 2024 UTC: INFO: BaseDB.py(1200): addValToDB db closed
17:36:34 15 May 2024 UTC: INFO: Base.py(2698): Processed files msg:
Processing complete as of 17:36:34 15 May 2024 GMT
p1950002.log
p1950002.eng
p1950002.asc
p1950002.cap
plots/dv0002_diveplot.div
plots/dv0002_diveplot.webp
plots/dv0002_cog.div
plots/dv0002_cog.webp
plots/dv0002_ctw.div
plots/dv0002_ctw.webp
plots/dv0002_aa4330.div
plots/dv0002_aa4330.webp
plots/dv0002_wlbb2fl_Chlorophyll_fluorescence.div
plots/dv0002_wlbb2fl_Chlorophyll_fluorescence.webp
plots/dv0002_wlbb2fl_backscatter.div
plots/dv0002_wlbb2fl_backscatter.webp
plots/dv0002_ctd.div
plots/dv0002_ctd.webp
plots/dv0002_raw_ctd.div
plots/dv0002_raw_ctd.webp
plots/dv0002_ts.div
plots/dv0002_ts.webp
plots/dv0002_ts_raw.div
plots/dv0002_ts_raw.webp
plots/dv0002_seabird_corr_compare.div
plots/dv0002_seabird_corr_compare.webp
plots/dv0002_vert_vel.div
plots/dv0002_vert_vel.webp
plots/dv0002_magcal.div
plots/dv0002_magcal.webp
plots/dv0002_diveplot.div
plots/dv0002_diveplot.webp
plots/dv0002_cog.div
plots/dv0002_cog.webp
plots/dv0002_ctw.div
plots/dv0002_ctw.webp
plots/dv0002_aa4330.div
plots/dv0002_aa4330.webp
plots/dv0002_wlbb2fl_Chlorophyll_fluorescence.div
plots/dv0002_wlbb2fl_Chlorophyll_fluorescence.webp
plots/dv0002_wlbb2fl_backscatter.div
plots/dv0002_wlbb2fl_backscatter.webp
plots/dv0002_ctd.div
plots/dv0002_ctd.webp
plots/dv0002_raw_ctd.div
plots/dv0002_raw_ctd.webp
plots/dv0002_ts.div
plots/dv0002_ts.webp
plots/dv0002_ts_raw.div
plots/dv0002_ts_raw.webp
plots/dv0002_seabird_corr_compare.div
plots/dv0002_seabird_corr_compare.webp
plots/dv0002_vert_vel.div
plots/dv0002_vert_vel.webp
plots/dv0002_magcal.div
plots/dv0002_magcal.webp
plots/eng_mission_volmax.div
plots/eng_mission_volmax.webp
plots/eng_download_stats.div
plots/eng_download_stats.webp
sg195.kmz
p1950002.nc
sg195_Shilshole_Overnight_OCN_201__15May2024_timeseries.nc

17:36:34 15 May 2024 UTC: INFO: Base.py(1363): Extension script /home/jails/uwssc/gliderjail/home/sg195/.post_mission not found
17:36:34 15 May 2024 UTC: INFO: BaseDB.py(1171): addValToDB db opened
17:36:34 15 May 2024 UTC: ERROR: Error inserting column capture - skipping:
Traceback (most recent call last):
  File "/usr/local/basestation3/BaseDB.py", line 120, in addColumn
    cur.execute(f"ALTER TABLE dives ADD COLUMN {col} {db_type};")
sqlite3.OperationalError: no such table: dives

17:36:34 15 May 2024 UTC: INFO: BaseDB.py(1200): addValToDB db closed
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /usr/local/basestation3/etc/.pagers for  alerts
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/sg1i1w4wpibg9m8s77e19st14w,slack,gpsddmm)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/71kp13t63ifummqbhxzniw18go,slack,alerts)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/5t1u7ab147dstbh5iq79h48spy,slack,critical)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /usr/local/basestation3/etc/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers for  alerts
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (7247147343@vtext.com,gps,alerts,recov)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /usr/local/basestation3/etc/.pagers for  alerts
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/sg1i1w4wpibg9m8s77e19st14w,slack,gpsddmm)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/71kp13t63ifummqbhxzniw18go,slack,alerts)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(621): Sending ALERTS FROM PROCESSING SG195 to https://sahale.apl.washington.edu/mattermost/hooks/71kp13t63ifummqbhxzniw18go
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(108): instrument_id:195 slack_hook_url:https://sahale.apl.washington.edu/mattermost/hooks/71kp13t63ifummqbhxzniw18go subject_line:ALERTS FROM PROCESSING SG195 message_body:ALERT:FM_IGNORE
    WARNING: volmax value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: rho0 value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: hd_a value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: hd_b value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: hd_c value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: abs_compress value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: therm_expan value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
    WARNING: temp_ref value ignored. v3 Flight Model does not use this value. Add '% FM_ignore' to sg_calib_constants.m to suppress this warning.
ALERT:MASS_MISMATCH
    WARNING: Mass of vehicle in sg_calib_constants (53692.0) does not match $MASS in log file (53765.0); using sg_calib_constants
Consult baselog_240515173602 for details.
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/5t1u7ab147dstbh5iq79h48spy,slack,critical)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /usr/local/basestation3/etc/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers for  alerts
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (7247147343@vtext.com,gps,alerts,recov)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(621): Sending ALERTS FROM PROCESSING SG195 to 7247147343@vtext.com
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /usr/local/basestation3/etc/.pagers for  alerts comp
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/sg1i1w4wpibg9m8s77e19st14w,slack,gpsddmm)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/71kp13t63ifummqbhxzniw18go,slack,alerts)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/5t1u7ab147dstbh5iq79h48spy,slack,critical)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /usr/local/basestation3/etc/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers for  alerts comp
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (7247147343@vtext.com,gps,alerts,recov)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /usr/local/basestation3/etc/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /home/jails/uwssc/gliderjail/home/sg195/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /usr/local/basestation3/etc/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /home/jails/uwssc/gliderjail/home/sg195/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /usr/local/basestation3/etc/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /home/jails/uwssc/gliderjail/home/sg195/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1041): Starting processing on .ftp
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1051): No .ftp file /usr/local/basestation3/etc/.ftp file found - skipping .ftp processing
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1061): Finished processing on .ftp
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1041): Starting processing on .sftp
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1051): No .sftp file /usr/local/basestation3/etc/.sftp file found - skipping .sftp processing
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1051): No .sftp file /home/jails/uwssc/gliderjail/home/sg195/.sftp file found - skipping .sftp processing
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1061): Finished processing on .sftp
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1426): Started processing on .mailer
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1438): No .mailer file /usr/local/basestation3/etc/.mailer file found - skipping .mailer processing
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(1451): Finished processing on .mailer
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(341): No .urls file /usr/local/basestation3/etc/.urls found - skipping pass 2
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(266): Starting processing on .urls pass(2)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(331): Finished processing on .urls pass(2)
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-2963492-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-15566-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-766373-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-19345-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-20485-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-2961317-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-766476-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: Utils.py(1845): notifying /tmp/sanic-16884-notify.ipc:195-urls-files:{"glider":195,"dive":2,"content":"files=all","time":1715794595.3603234}
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /usr/local/basestation3/etc/.pagers for  errors
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/sg1i1w4wpibg9m8s77e19st14w,slack,gpsddmm)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/71kp13t63ifummqbhxzniw18go,slack,alerts)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (https://sahale.apl.washington.edu/mattermost/hooks/5t1u7ab147dstbh5iq79h48spy,slack,critical)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(414): Using sending function slack
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /usr/local/basestation3/etc/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(401): Starting processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers for  errors
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(409): Processing .pagers line (7247147343@vtext.com,gps,alerts,recov)
17:36:35 15 May 2024 UTC: INFO: BaseDotFiles.py(672): Finished processing on /home/jails/uwssc/gliderjail/home/sg195/.pagers
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /usr/local/basestation3/etc/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: BaseCtrlFiles.py(262): No ctrl file /home/jails/uwssc/gliderjail/home/sg195/pagers.yml found - skipping
17:36:35 15 May 2024 UTC: INFO: Base.py(3001): Finished processing 17:36:35 15 May 2024 GMT
